Repository dev-house-community/EarphoneJack, pull requests merged in 2021-05, with the labels that each got.

#11 Criando aquivo LICENSE
  LICENSE.md
Labels: documentation

#14 Alterando estruturas de arquivos
  src/commands/list.ts
  src/commands/play.ts
  src/commands/skip.ts
  src/commands/stop.ts
  src/commands/volume.ts
  src/index.ts
Labels: enhancement

#18 Added help command
  src/commands/help.ts
Labels: enhancement

#19 Adicionando um banco de dados
  .gitignore
  ormconfig.json
  package.json
  src/commands/create.ts
  src/commands/list.ts
  src/commands/play.ts
  src/commands/show.ts
  src/commands/volume.ts
  src/controllers/MusicController.ts
  src/database/PlaylistRepository.ts
  src/database/connection.ts
  src/database/database.example.sqlite
  src/database/migrations/1620086054846-CreatePlaylist.ts
  src/database/migrations/1620171366267-CreateSongs.ts
  src/index.ts
  src/models/Playlist.ts
  src/models/Song.ts
  src/utils/AddToPlaylist.ts
  src/utils/GetVideoId.ts
  src/utils/SongInfo.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#25 Feature: Adicionando comando remove
  src/commands/help.ts
  src/commands/list.ts
  src/commands/remove.ts
  src/commands/show.ts
  src/database/PlaylistRepository.ts
Labels: enhancement

#29 Adicionando configurações de produção
  .gitignore
  tsconfig.json
Labels: help wanted

#32 Documentation: Atualizando README.md
  README.md
Labels: documentation

#33 Issues Requisição HTTP para mandar mensagem #30
  src/controllers/SendMessagesController.ts
  src/shared/infra/http/routes/messages.route.ts
Labels: enhancement, help wanted
